services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./next.config.ts:/app/next.config.ts
      - ./package.json:/app/package.json
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
